theme                    : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Minimal Mistakes"
title_separator          : "-"
subtitle                 : "Development Test Site"
name                     : "Your Name"
description              : "Minimal Mistakes theme test."
