name: Pavel Kuznetsov CV
title: Niritum
author: Niritum
logo: "/assets/images/logo.png"

remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-paginate
 
paginate: 5  # amount of posts to show per page
paginate_path: /page:num/
